version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: optiverse_db
    environment:
      POSTGRES_USER: optiverse_user
      POSTGRES_PASSWORD: optiverse_password
      POSTGRES_DB: optiverse_db
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: optiverse_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: 